Repository wprig/wprig, pull requests merged in 2018-11, with the labels that each got.

#146 Fix PHPCompatibility issues in Travis-CI
  .travis.yml
  dev/functions.php
Labels: bug

#164 Force refresh assets
  inc/assets.php
  pluggable/lazyload/lazyload.php
Labels: enhancement

#194 FIX #167: Simplify README.md by moving documentation to dedicated Wiki pages
  README.md
Labels: documentation
